name: Daily Commit Tracker

on:
  schedule:
    # Run daily at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup timezone
      run: |
        sudo timedatectl set-timezone UTC
        
    - name: Create logs directory
      run: mkdir -p logs
      
    - name: Update activity logs
      run: |
        TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S UTC')
        echo "Daily activity commit - $TIMESTAMP" >> logs/daily-activity.log
        echo "Last updated: $TIMESTAMP" > logs/last-update.txt
        
        # Update streak count
        if [ ! -f logs/streak-count.txt ]; then
          echo "1" > logs/streak-count.txt
        else
          CURRENT_STREAK=$(cat logs/streak-count.txt)
          NEW_STREAK=$((CURRENT_STREAK + 1))
          echo "$NEW_STREAK" > logs/streak-count.txt
        fi
        
        # Update streak info
        if [ ! -f logs/streak-info.txt ]; then
          START_DATE=$(date '+%Y-%m-%d')
          echo "Streak started: $START_DATE" > logs/streak-info.txt
        fi
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add logs/
        git commit -m "Daily activity update - $(date '+%Y-%m-%d %H:%M:%S UTC')" || exit 0
        git push
        
  deploy-pages:
    needs: update-activity
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4