name: Daily Repository Activity

on:
  schedule:
    # Run every day at 7:30 AM IST (2:00 AM UTC = 7:30 AM IST)
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering for testing

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write # Required for pushing commits
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Fetch full history for proper git operations
      
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Create or update activity log
        run: |
          # Create logs directory if it doesn't exist
          mkdir -p logs
          
          # Get current timestamp in IST (UTC+5:30)
          UTC_TIME=$(date -u '+%Y-%m-%d %H:%M:%S')
          IST_TIME=$(TZ='Asia/Kolkata' date '+%Y-%m-%d %H:%M:%S IST')
          
          # Append timestamp to activity log
          echo "Daily activity commit - $IST_TIME" >> logs/daily-activity.log
          
          # Also update a status file with just the latest timestamp
          echo "Last updated: $IST_TIME" > logs/last-update.txt
      
      - name: Check for changes
        id: verify-changed-files
        run: |
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes detected"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changes == 'true'
        run: |
          IST_TIME=$(TZ='Asia/Kolkata' date '+%Y-%m-%d %H:%M:%S IST')
          
          # Add all changes in logs directory
          git add logs/
          
          # Commit with timestamp
          git commit -m "🤖 Daily activity update - $IST_TIME" -m "Automated commit to maintain repository activity"
          
          # Push changes
          git push origin ${{ github.ref_name }}
      
      - name: Log completion
        run: |
          if [[ "${{ steps.verify-changed-files.outputs.changes }}" == "true" ]]; then
            echo "✅ Daily commit completed successfully"
          else
            echo "ℹ️ No changes to commit (this shouldn't normally happen)"
          fi
      
      - name: Handle errors
        if: failure()
        run: |
          echo "❌ Daily commit workflow failed"
          echo "Please check the workflow logs for details"
          exit 1
